# CONFIGURATIONS FOR THE SIMULATION.
#python3 manage.py --mcore fd --s condor
#python3 manage.py  --acc fv --s slurm
#----------------------------------------------------------------#

# Spatial domain specifics.
zrange: [-0.1, 0.1]
nzs: [1,10,100,500,1000] #[3600]
CFLS: [1,0.5,0.1,0.01]
#CFLS: [0.0001,0.001]

#----------------------------------------------------------------#

# Phase-space specifics.
v0: -1.0
v1: 1.0
nvzs: [2] #[2,8,32,64,90,180] #[32]

#----------------------------------------------------------------#

boundary: periodic # Options ->  periodic, open

#----------------------------------------------------------------#

end_time: 200 # Physical end time

#----------------------------------------------------------------#

perturbation_size: 1e-2 #1e-2

#----------------------------------------------------------------#

# Switch on/off advection.
advection_off: True # Options -> True, False

# Switch on/off vacuum oscillation
vac_osc_on: True # options -> True, False
pmo: 1.0 # 1.0 -> normal mass ordering, -1.0 -> inverted mass ordering, 0.0 -> no vacuum term.
omega: 0.01 #1e-2 #1.0 #1e-4 \Dedlta m^2/2E.
theta: 0 # 37 Vacuum mixing angle in degrees.

mat_osc_on:  True #True

# Switch on/off collective oscillations
collective_osc_on: True # Options -> True, False
mu: 1.0 #1.0 \sqrt{2} G_F n_{\nu_e}
#----------------------------------------------------------------#
# ANALYSIS
#----------------------------------------------------------------#

# To analyze the behaviour of the conserved quantities.
n_analyze: 100 # Total number of analysis to be carried out per job.

# To capture the the field variables for all the velocities over entire domain.
n_dump_rho: 100 # number of times density matrix elements has to be dumped.

#----------------------------------------------------------------#

# Folder names
folder_fv: "fv_sl_sajm_rdp_yvymys_nnm_NN_Z01_A2_tur2_r_mu_100_Lmu_3_ar_0.7_run1"
folder_fd: "fd_sl_sajm_rdp_yvymys_nnm_NN_Z01_A2_tur2_r_mu_100_Lmu_3_ar_0.7_run1" #"output_from_fd"
#fd_hetg_24_flat_rap_inm_mu_100_Lmu_300_ar_0.7_run1

#----------------------------------------------------------------#

condor_requests:
  ncpu: 12
  ram: 10G
  storage: 20G
  
slurm_requests: #slurm job description
  GPU:
    enable: False
    partition: v100_long #a100
    ngres: 1

  
  CPU:
    enable: True
    cpus-per-task: 20
    # partition: long_serial
    partition: edr1_long_serial
    purge: purge

modules: ["nvhpc/24.3"]